//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carriers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carriers()
        {
            this.Goods = new HashSet<Goods>();
        }
    
        public int CarriersID { get; set; }
        public int SchedulingID { get; set; }
        public string CarriersId { get; set; }
        public string SendCompany { get; set; }
        public string SendAddress { get; set; }
        public string SendLinkman { get; set; }
        public string SendPhone { get; set; }
        public string ReceiveCompany { get; set; }
        public string ReceiveAddress { get; set; }
        public string ReceiveLinkman { get; set; }
        public string ReceivePhone { get; set; }
        public Nullable<System.DateTime> LeaverDate { get; set; }
        public string LeaverDateS { get; set; }
        public string LeaverDateE { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string ReceiveDateS { get; set; }
        public string ReceiveDateE { get; set; }
        public byte FinishedState { get; set; }
        public Nullable<double> InsuranceCost { get; set; }
        public Nullable<double> TransportCost { get; set; }
        public Nullable<double> OilCost { get; set; }
        public Nullable<double> Toll { get; set; }
        public Nullable<double> Fine { get; set; }
        public Nullable<double> OtherCost { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> TotalCostS { get; set; }
        public string Remark { get; set; }
        public string UserName { get; set; }
        public int FK_UserID { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public byte IsDelete { get; set; }
        public Nullable<System.DateTime> AlterTime { get; set; }
     public string StartTime { get; set; }
        public virtual Carriers Carriers1 { get; set; }
        public virtual Carriers Carriers2 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goods> Goods { get; set; }
    }
}
