//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public Nullable<int> FK_TruckID { get; set; }
        public Nullable<int> FK_DriverID { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Truck Truck { get; set; }
    }
}
