//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsManagerModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogisticsEntities : DbContext
    {
        public LogisticsEntities()
            : base("name=LogisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carriers> Carriers { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<LogDic> LogDic { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Scheduling> Scheduling { get; set; }
        public virtual DbSet<SysLog> SysLog { get; set; }
        public virtual DbSet<Truck> Truck { get; set; }
        public virtual DbSet<TruckTeam> TruckTeam { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
