//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduling
    {
        public int SchedulingID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> FK_CarriersID { get; set; }
        public Nullable<int> FK_TruckID { get; set; }
        public Nullable<double> OilCost { get; set; }
        public Nullable<double> Toll { get; set; }
        public Nullable<double> Fine { get; set; }
        public Nullable<double> OtherCost { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<byte> IsDelete { get; set; }
        public Nullable<System.DateTime> AlterTime { get; set; }
    
        public virtual Truck Truck { get; set; }
        public virtual User User { get; set; }
    }
}
