//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsManagerModel
{
    using System;
    using System.Collections.Generic;

    public partial class SysLog
    {
        public int LogID { get; set; }
        public string Behavior { get; set; }
        public Nullable<int> FK_TypeID { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public string Account { get; set; }
        public string Parameters { get; set; }
        public string ProcName { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public string CheckInTimeS { get; set; }
        public string CheckInTimeE { get; set; }
        public string Exception { get; set; }
        public Nullable<byte> IsException { get; set; }

        public virtual LogDic LogDic { get; set; }
        public virtual User User { get; set; }
    }
}
