//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truck()
        {
            this.Contact = new HashSet<Contact>();
            this.Scheduling = new HashSet<Scheduling>();
        }
    
        public int TruckID { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public string Type { get; set; }
        public string Length { get; set; }
        public Nullable<int> Tonnage { get; set; }
        public Nullable<int> FK_TeamID { get; set; }
        public int State { get; set; }
        public string StateName { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public byte IsDelete { get; set; }
        public Nullable<System.DateTime> AlterTime { get; set; }
        public string TeamName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scheduling> Scheduling { get; set; }
        public virtual TruckTeam TruckTeam { get; set; }
    }
}
