//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TruckTeam()
        {
            this.Driver = new HashSet<Driver>();
            this.Truck = new HashSet<Truck>();
        }
    
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string Leader { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public byte IsDelete { get; set; }
        public Nullable<System.DateTime> AlterTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Truck> Truck { get; set; }
    }
}
